### ISSUE TITLE
Sensor Names Incorrect

### ISSUE THREAD

**Issue by craigmate** [bremor/public_transport_victoria#2]
HI.  I found your repo on and just want to let you know of a couple of small bugs.  I don't know if you are still maintaining it and of course, it isn't likely I will be using public transport for the rest of the year, but it seems like it will be a useful tool once we are allowed to go into the office. 

I set it up correctly with the User ID and API key and it appeared to work fine.  (I already had these as I previously had been using a rest sensor to get the information)

However I did notice that the sensor name were called sensor.example_temperature sensor.example_temperature_1  etc
Also the friendly name was Example Temperature

Anyway, just thought I would let you know, as this is potentially a very useful custom component for when life gets back to something resembling normality.

Thanks again...

**Comment by bremor** [comment]
Thanks mate! I am getting this repo ready for a larger audience at some point in October (planning to release on HACS), so it will be good to have someone to help with testing 👍 I am definately still maintaining it, it is still very much in an alpha stage though.  Try using the latest v 0.1. Should be better, but i'm sure there are more bugs since I have only done limited testing.

**Comment by craigmate** [comment]
Thanks for the updates.  They are really good.  Just one thing I did notice, it appears your Developer ID/Developer Key are hard coded into the integration.  When I went to add it, the keys were there.  I did end up using my key, but thought you might want to know, if they ever put in api call limits.

**Comment by bremor** [comment]
Thanks for your help with testing. I have submitted a PR to have this put on the default HACS store. Please let me know if you  run into any other issues.
